findById:
   grpcurl -plaintext -d "1" localhost:50051 org.eaip.user.AccountService/findById

findByStatus:
   grpcurl -plaintext -d "1" localhost:50051 org.eaip.user.AccountService/findByStatus

findByIdStream:
   grpcurl -plaintext -d @ localhost:50051 org.eaip.user.AccountService/findByIdStream

services:
   grpcurl -plaintext localhost:50051 list