global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'eaip-rsocket-brokers'
    file_sd_configs:
      - files:
          # http://localhost:9998/metrics/prometheus/broker/targets
          - '/etc/prometheus/eaip-rsocket-brokers.json'
  - job_name: 'eaip-rsocket-apps'
    file_sd_configs:
      - files:
          # http://localhost:9998/metrics/prometheus/app/targets
          - '/etc/prometheus/eaip-rsocket-apps.json'
